# Generated by Django 6.0.3 on 2026-04-11 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_cryptocurrency_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradehistory',
            name='trader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tradehistory', to=settings.AUTH_USER_MODEL),
        ),
    ]
