# Generated by Django 6.0.3 on 2026-04-11 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_tradehistory_trader'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyorder',
            name='buyer',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='buy_orders', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sellorder',
            name='seller',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='sell_orders', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
