# Generated by Django 6.0.3 on 2026-04-13 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_buyorder_buyer_sellorder_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='stored_state',
            field=models.JSONField(null=True),
        ),
    ]
