# Generated by Django 6.0.3 on 2026-04-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_algorithm_stored_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='algorithm_token_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='algorithm',
            name='token_cache_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
