# Generated by Django 6.0.3 on 2026-04-14 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_membership_accepted'),
        ('api', '0007_algorithmtoken'),
    ]

    operations = [
    ]
